"""markdown feature

Revision ID: 15f658cedd5b
Revises: 736ed7884b38
Create Date: 2016-09-19 21:16:04.745498

"""

# revision identifiers, used by Alembic.
revision = '15f658cedd5b'
down_revision = '736ed7884b38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
