"""add avatar

Revision ID: 8b66aefdf094
Revises: c9b5b1d19b63
Create Date: 2016-09-17 20:56:32.695703

"""

# revision identifiers, used by Alembic.
revision = '8b66aefdf094'
down_revision = 'c9b5b1d19b63'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
