"""insert roles

Revision ID: ce190b019f13
Revises: 2b66b10f5dd1
Create Date: 2016-09-14 22:36:27.895263

"""

# revision identifiers, used by Alembic.
revision = 'ce190b019f13'
down_revision = '2b66b10f5dd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permission', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permission')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
